#!/bin/bash

set -ex


command=${1}

DATABASE_URL="postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=${POSTGRES_SSL_MODE}"
case "${command}" in
  "worker")
    goose -dir /app/migrations postgres "${DATABASE_URL}" up
    gecko worker
    ;;
  "serve")
    goose -dir /app/migrations postgres "${DATABASE_URL}" up
    gecko serve
    ;;
  "migrate")
    goose -dir /app/migrations postgres "${DATABASE_URL}" up
    ;;
  *)
    # Pass through all arguments to gecko
    gecko "$@"
    ;;
esac

