FROM debian:bookworm-slim AS litestream

ARG TARGETPLATFORM
ARG litestream_version="v0.3.9"

WORKDIR /litestream

RUN set -x && \
    apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
      ca-certificates \
      wget

RUN set -x && \
    if [ "$TARGETPLATFORM" = "linux/arm/v7" ]; then \
      ARCH="arm7" ; \
    elif [ "$TARGETPLATFORM" = "linux/arm64" ]; then \
      ARCH="arm64" ; \
    else \
      ARCH="amd64" ; \
    fi && \
    set -u && \
    litestream_binary_tgz_filename="litestream-${litestream_version}-linux-${ARCH}-static.tar.gz" && \
    wget "https://github.com/benbjohnson/litestream/releases/download/${litestream_version}/${litestream_binary_tgz_filename}" && \
    mv "${litestream_binary_tgz_filename}" litestream.tgz
RUN tar -xvzf litestream.tgz

FROM golang:{{ cookiecutter.go_version}} AS builder

WORKDIR /build

# only copy mod file for better caching
COPY ../../go.mod go.mod
RUN go mod download

COPY ../.. .

RUN apt-get install git &&\
    go build  \
    -ldflags="-s -w" \
    -o {{ cookiecutter.cmd_name.strip()}} \
     ./cmd/{{ cookiecutter.cmd_name.strip()}}

FROM debian:bookworm-slim

WORKDIR /app
COPY --from=builder ["/build/litestream.yml", "/app/litestream.yml"]
COPY --from=builder ["/build/entrypoint", "/app/entrypoint"]
COPY --from=builder ["/build/app", "/usr/bin/app"]
COPY --from=litestream ["/litestream/litestream", "/usr/bin/litestream"]

# ensures that migrations are run using the embedded files
ENTRYPOINT ["/app/entrypoint"]
CMD ["app", "serve"]
