# this is only needed for local development. it allows for hot-reloading of the server
# omit this in production
root = "."
tmp_dir = "tmp"

[build]
bin = "./tmp/{{ cookiecutter.cmd_name.strip() }}"
cmd = "go build -o ./tmp/{{ cookiecutter.cmd_name.strip() }} ./cmd/{{ cookiecutter.cmd_name.strip() }}"
delay = 1000
exclude_dir = ["node_modules", "tmp", "vendor"]
exclude_file = []
exclude_regex = []
exclude_unchanged = false
follow_symlink = false
full_bin = ""
include_dir = []
include_ext = ["go", "tpl", "tmpl", "html", "css", "js"]
kill_delay = "0s"
log = "build-errors.log"
send_interrupt = false
stop_on_error = true

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
time = false

[misc]
clean_on_exit = false
