services:
  {{ cookiecutter.project_name }}-db:
    image: postgres:16-alpine
    container_name: {{ cookiecutter.project_name }}-db
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - {{ cookiecutter.project_name }}_network
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    healthcheck:
      test: [CMD-SHELL, pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB]
      interval: 10s
      retries: 5
      timeout: 5s
    volumes:
      - {{ cookiecutter.project_name }}-db:/var/lib/postgresql/data:Z

volumes:
  {{ cookiecutter.project_name }}_db:

networks:
  {{ cookiecutter.project_name }}_network:
